{% set name = "kedro-mlflow" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kedro_mlflow-{{ version }}.tar.gz
  sha256: d357e43f6b093890e351973313e5cbdbd7871b108d165cf641e8712ae3823f78

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools-scm
    - pip
  run:
    - python >=3.8,<3.12
    - kedro >=0.19.0,<0.20.0
    - kedro-datasets
    - mlflow >=1.0.0,<3.0.0
    - pydantic >=1.0.0,<3.0.0

test:
  imports:
    - kedro_mlflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Galileo-Galilei/kedro-mlflow
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: A Kedro plugin to use mlflow in your Kedro projects
  description: |
    kedro-mlflow is a Kedro plugin for lightweight and portable integration of mlflow capabilities inside kedro projects.
    It enforces Kedro principles to make mlflow usage as production ready as possible. 
    Its core functionalities are versioning and model packaging.
  doc_url: https://kedro-mlflow.readthedocs.io/
  dev_url: https://github.com/Galileo-Galilei/kedro-mlflow

extra:
  recipe-maintainers:
    - Galileo-Galilei
